# ----------------------------------------------------------------------------------------------------------------
# RL_PtG: Deep Reinforcement Learning for Power-to-Gas Dispatch Optimization
# https://github.com/SimMarkt/RL_PtG

# config_train: 
# > Configuration file for setting up training
# ----------------------------------------------------------------------------------------------------------------
          
com_conf : pc               # Computational resources to be used: 
                            # 'pc' (local personal computer) or 'slurm' (computing cluster with SLURM management)
device : auto               # Computational device to use: ['cpu', 'cuda', 'auto']
                            # 'auto' selects GPU if available, otherwise defaults to CPU
str_inv : train             # Specifies the training results and models for a specific investigation

train_steps : 1500000         # No. of training steps
val_steps : 20000            # Validation interval: No. of steps between evaluations during training
# Random seeds for reproducibility of neural network initialization and environment randomness:
r_seed_train : [3654, 467, 9327, 5797, 249, 9419]         # Random seeds for the training set (default: [3654] for single-threaded computations)
r_seed_test : [605, 5534, 2910, 7653, 8936, 1925]         # Random seeds for the validation set (default: [605] for single-threaded computations)