# -------------------------------------------------------------------------------------------------
# MCTS_Q: Monte Carlo Tree Search with Deep-Q-Network
# GitHub Repository: https://github.com/SimMarkt/MCTS_Q
#
# config_train: 
# > Configuration file for setting up training
# -------------------------------------------------------------------------------------------------
          
com_conf : pc  # Computational resources: 'pc' (local) or 'slurm' (SLURM cluster)

# Computational device to use: ['cpu', 'cuda', 'auto']
# 'auto' selects GPU if available, otherwise defaults to CPU
device : auto

str_inv : train  # Specifies the training results and models for a specific investigation

# Model config: 'simple_train', 'save_model', 'load_model', 'save_load_model'
# 'simple_train': Train the RL model from scratch
# 'save_model': Train the RL model from scratch and save it afterward
# 'load_model': Load a pretrained RL model and continue training
# 'save_load_model': Load a pretrained RL model, continue training, and save the updated model
model_conf : simple_train

log_path : /logs/           # Path to save the MTCS_Q model
tb_path : /tensorboard/     # Tensorboard path

train_steps : 10000000  # No. of training steps
val_steps : 40000       # Validation interval: No. of steps between evaluations during training
# Random seeds for reproducibility of neural network initialization and environment randomness:
r_seed_train : [3654, 467, 9327, 5797, 249, 9419]  # for training (default: [3654] for single-threaded computations)
r_seed_test : [605, 5534, 2910, 7653, 8936, 1925]  # for validation (default: [605] for single-threaded computations)
