# ----------------------------------------------------------------------------------------------------------------
# MCTS_Q: Monte Carlo Tree Search with Deep-Q-Network
# GitHub Repository: https://github.com/SimMarkt/MCTS_Q
#
# config_mcts: 
# > Configuration file for the MTCS in the PtG-CH4 environment
# > The algorithm uses Upper Confidence Bound for Trees (UCT) to balance exploration and exploitation
# ----------------------------------------------------------------------------------------------------------------

# MCTS hyperparameters
iterations : 50           # No. of iterations for MCTS
c_init : 1.0                # Initial exploration parameter for PUCT
c_base : 10                # Parameter for exploration increase in PUCT
maximum_depth : 72          # Maximum depth of the tree

# Q-Learning hyperparameters
learning_rate : 0.001       # Learning rate
discount_factor : 0.99      # Discount factor for future rewards
epsilon_start : 1.0         # Initial exploration rate
epsilon_end : 0.1           # Final exploration rate
epsilon_decay : 0.995       # Decay rate for exploration
hidden_layers : 2           # Number of hidden layers in the MLP head of the DQN model
hidden_units : 128          # Number of hidden units in the DQN model
buffer_size : 100000        # Size of the replay buffer
batch_size : 64             # Batch size for training
activation : "relu"         # Activation function for the DQN model ("relu", "tanh")
learning_starts : 5       # Number of steps before starting to learn

# Encoder hyperparameters
seq_length : 30               # Length of the sequence for time-series encoding
seq_step : 10                 # Number of data steps in process data (2-Sec resolution) between two consequitive entries in the sequence (30 steps = 60 seconds)
embed_dim : 64                # Dimension of the embedding layer
price_encoder_type : "conv"   # Type of encoder for price data [Conv1D: "conv", GRU: "gru", Transformer: "transformer"]
process_encoder_type : "conv" # Type of encoder for process data [Conv1D: "conv", GRU: "gru", Transformer: "transformer"]
gas_eua_encoder_type : "gru"  # Type of encoder for gas EUA data [Feed forward: "mlp", GRU: "gru"]

# Additional settings
path_log : "/logs/"         # Path to save the logs of the tree structure
store_interval : 1000       # No. of simulation steps after which the tree structure is logged into a csv file

  

